/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AInput: typeof import('ant-design-vue/es')['Input']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    CodeTextarea: typeof import('./src/components/CodeTextarea.vue')['default']
    Heap: typeof import('./src/components/Heap.vue')['default']
    StatItem: typeof import('./src/components/StatItem.vue')['default']
    StatList: typeof import('./src/components/StatList.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}
